* Day 2 instructions
After we finished day 1, we now essentially have all the components needed to start building a system

** Day2 Part 1 - Setting up GitHub action for controlling Azure ML
We need to configure GitHub Actions to execute our orchestration scripts. We will first make it so we can automatically build a custom runner for our workflows. We will then connect GitHub actions to our Azure ML workspace using a Service Principle and GitHub secrets. You find the instructions [[./github-day-1.org][here]].

** Day 2 Part 2 - Continuous Training
We create workflows that runs the training pipeline. We will modify our existing pipeline as to register build information when training models and will use this to automatically deploy a new version of the web service if the model was updated. You find the instructions [[./day-2-continuous-training.org][here]].

** Day 2 Part 3 Continuous Deployment
We will add workflows to run a smoke test of new deployment whenever the code for the web service changes or a new model is registered. We then update the existing webservice if the new webservice completes the tests succesfully. You find the instructions [[./day2-continuous-deployment.org][here]].

** Day 2 Part 4 - Continuous Integration
Continuous Integration, in this case, means updating our published pipeline when there are any relevant changes to the pipeline code. We also want to make sure that we don't publish any subpar pipelines that don't improve or prouces worse results. You find the instructions [[./day2-continuous-integration.org][here]].

** No Continuous Monitoring?
Maybe in day 3.
