#+title: Instructions for MLOps Workshop Day 1

* Preparations

** What is MLOps
Before you start you might want to read a small introduction of [[./mlops.org][MLOps.]]

** Preparing for the Workshop / Masterclass
*** Example Code
We frequently reference this [[https://github.com/lukas-lundmark/mlops-example][example repository]]. This respository serves to purposes. First, we will use some files here as the base for our own project. Second, you may use the scripts there as reference for your own implementation if you are unsure about something.

*** Data
We will use the commonly used Diamond dataset in our experiments. You can find a training and test split of the dataset in the Google Drive here.


*** Tools and Utilities

**** Python
Python is the go-to tool for everything in Data Science and Data Engineering. To have an easier time developing, it is important to have a good setup for Python, where you can manage your dependencies and your environments with ease.

You can find some instructions for how to prepare your python environment [[./setup-python.org][here]], along with some thoughts on how one should manage python environment in general.

Note: M1 Users can look [[./m1.org][here]] for how they should set up their environment.

**** Docker
Since we will execute code both locally and on the cloud we will use Docker to define a consistent runtime environment for our code to run in.

Read a Docker Introduction and installation information [[./docker.org][here]].

**** Azure and Azure ML
Azure ML is one of many ML-as-a-Service offerings that exist on the market. There is nothing unique about it, but it allows us to manage almost every step of the model life-cycle using a single, and consistent API, which makes it good for learning.

Instructions for how to get started with Azure and Azure ML can be found [[./setup-azure.org][here]].

**** GitHub
We will use GitHub as our Code Repository and GitHub Actions as our CI/CD environment. You can create a new GitHub account for free, or use the GitHub account you use for your Solita work. GitHub Actions works for all versions of GitHub, so it doesn't matter which account you use.

You can read a basic introduction to GitHub Actions [[./github-info.org][here]].
**** Command Line
We will make heavy use of the command line. Most commands in the examples should work on both Windows CMD and Unix shells. However, if you are on Windows you might want to consider downloading a more Unix-y terminal, such as the GitBash, or CMder.

* Day 1 Instructions

Day 1 Presentation can be found [[https://docs.google.com/presentation/d/1NFbbvjmwhlM5d4xiPC8n6wXoMj9552jhWzCr8yJVTmg/edit?usp=sharing][here]]
Data for the workshop can be found here
Example Repo with Code examples can be found here

** Day1 Part 1 - Getting Started with Azure ML
We start by setting up an experiment locally using [[./azureml-info.org][Azure ML]] to train our model in a notebook. You find the instructions [[./azureml-day-1.org][here]].

** Day1 Part 2 - Deploying a Model
We go through common ways to deploy models and play around with local and cloud deployment in Azure ML. You find the instructions [[./deployments-day1.org][here]].

** Day1 Part 3 - From Notebooks to Pipelines
We convert our notebook to a training script and an ML pipeline that we run on remote compute.
You find the instructions [[./azureml-pipelines.org][here]].

* Relevant Litterature
- Practical MLOps
